### ISSUE TITLE
About training the model.

### ISSUE THREAD

**Issue by sdp369** [Jia-Research-Lab/Context-Aware-Consistency#22]
I try to train the model as your guide ( python3 train.py --config configs/voc_cac_deeplabv3+_resnet50_1over8_datalist0.json
),  but the program is ended with an error.  Can you give me some suggestions？

The error :
Traceback (most recent call last):
  File "/home/anaconda3/envs/sdp36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/sundingpeng/paper_code/Context-Aware-Consistency-master/train.py", line 98, in main
    trainer.train()
  File "/home/sundingpeng/paper_code/Context-Aware-Consistency-master/base/base_trainer.py", line 113, in train
    self._train_epoch(epoch)
  File "/home/sundingpeng/paper_code/Context-Aware-Consistency-master/trainer.py", line 81, in _train_epoch
    curr_iter=batch_idx, target_ul=target_ul, epoch=epoch-1, **kargs)
  File "/home/anaconda3/envs/sdp36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/sdp36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/sdp36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sundingpeng/paper_code/Context-Aware-Consistency-master/models/model.py", line 174, in forward
    selected_idx1 = np.random.choice(range(b*h*w), selected_num, replace=False)
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

**Comment by X-Lai** [comment]
Thanks for your interest in our work.

May I ask whether you have changed the batch_size or the number of gpus? If yes, you may change to the default setting or calculate the `selected_num` for your customized setting manually.

According to the error, I guess the problem is the `selected_num` is greater than the number of available features during negative sampling. Normally, `selected_num` should be smaller than `batch_size / n_gpu` * `crop_size / stride`^2 * (`step_save+1`).
